language: php
php:
- 5.6
- 5.5
- hhvm

before_script:
  - composer install --dev

script:
    - vendor/bin/phpunit --coverage-clover=coverage.xml

after_success:
    - bash <(curl -s https://codecov.io/bash)
